name: Collaborative Workflow

on:
  push:
    branches:
      - main

jobs:
  update_html_and_readme:
    runs-on: ubuntu-latest
    steps:
    # Step 1: Checkout the repository
    - name: Checkout Repository
      uses: actions/checkout@v3
      
   # Step 2: Update Index HTML
    - name: Update HTML
      run: |
        # Team Leader Update index.HTML
        if [ "${{ github.actor }}" == "DTK-UTS" ]; then
          sed -i '/<\/body>/i <p>Updated by Team Leader on '"$(date)"'</p>' index.html
        fi

